### PR TITLE
grimoire update

### PR DESCRIPTION
**Pull request by noisesmith**
updates from @arrdem, vetted by me, to work with the latest conj.io

### CODE REVIEW

**Comment by Raynes** [comment]
Do we have to depend on an alpha?

**Comment by arrdem** [comment]
No, I can promote this to full 0.9 with some more work, but the reach set of these patches will be unchanged by the work I need to do to get a full release out the door.

**Comment by arrdem** [comment]
lib-grimoire 0.9.0 finished to my satisfaction and live. PR update incomming.

**Comment by noisesmith** [comment]
@Raynes this should address your concern? I just ran it, still looks good.

**Pull request merged**
